name: storm_lang
description: A programing language entry to repl.it's programming challenge
version: 0.0.1
homepage: https://github.com/HarryET/stormlang

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  console: ^4.1.0
